<?php
// config/menus/bootstrap.php

return [
    [
        'title'   => 'Bootstrap',
        'icon'    => 'Shopping/Box2',
        'submenu' => [
            [ 'title' => 'Typography',     'route' => '/features/bootstrap/typography' ],
            [ 'title' => 'Buttons',        'route' => '/features/bootstrap/buttons' ],
            [ 'title' => 'Button Group',   'route' => '/features/bootstrap/button-group' ],
            [ 'title' => 'Dropdown',       'route' => '/features/bootstrap/dropdown' ],
            [ 'title' => 'Navs',           'route' => '/features/bootstrap/navs' ],
            [ 'title' => 'Tables',         'route' => '/features/bootstrap/tables' ],
            [ 'title' => 'Progress',       'route' => '/features/bootstrap/progress' ],
            [ 'title' => 'Modal',          'route' => '/features/bootstrap/modal' ],
            [ 'title' => 'Alerts',         'route' => '/features/bootstrap/alerts' ],
            [ 'title' => 'Popover',        'route' => '/features/bootstrap/popover' ],
            [ 'title' => 'Tooltip',        'route' => '/features/bootstrap/tooltip' ],
        ],
    ],
    [
        'title'   => 'Custom',
        'icon'    => 'Files/Pictures1',
        'submenu' => [
            [ 'title' => 'Utilities',      'route' => '/features/custom/utilities' ],
            [ 'title' => 'Labels',         'route' => '/features/custom/label' ],
            [ 'title' => 'Pulse',          'route' => '/features/custom/pulse' ],
            [ 'title' => 'Line Tabs',      'route' => '/features/custom/line-tabs' ],
            [ 'title' => 'Advance Navs',   'route' => '/features/custom/advance-navs' ],
            [ 'title' => 'Timeline',       'route' => '/features/custom/timeline' ],
            [ 'title' => 'Pagination',     'route' => '/features/custom/pagination' ],
            [ 'title' => 'Symbol',         'route' => '/features/custom/symbol' ],
            [ 'title' => 'Overlay',        'route' => '/features/custom/overlay' ],
            [ 'title' => 'Spinners',       'route' => '/features/custom/spinners' ],
            [ 'title' => 'Iconbox',        'route' => '/features/custom/iconbox' ],
            [ 'title' => 'Callout',        'route' => '/features/custom/callout' ],
            [ 'title' => 'Ribbons',        'route' => '/features/custom/ribbons' ],
            [ 'title' => 'Accordions',     'route' => '/features/custom/accordions' ],
        ],
    ],
    [
        'title'   => 'Cards',
        'icon'    => 'Layout/Layout-arrange',
        'submenu' => [
            [ 'title' => 'General Cards',  'route' => '/features/cards/general' ],
            [ 'title' => 'Stacked Cards',  'route' => '/features/cards/stacked' ],
            [ 'title' => 'Tabbed Cards',   'route' => '/features/cards/tabbed' ],
            [ 'title' => 'Draggable Cards','route' => '/features/cards/draggable' ],
            [ 'title' => 'Cards Tools',    'route' => '/features/cards/tools' ],
            [ 'title' => 'Sticky Cards',   'route' => '/features/cards/sticky' ],
            [ 'title' => 'Stretched Cards','route' => '/features/cards/stretched' ],
        ],
    ],
    [
        'title' => 'Widgets',
        'icon'  => 'Devices/Diagnostics',
        'submenu' => [
            ['title' => 'Lists',           'route' => '/features/widgets/lists'],
            ['title' => 'Stats',           'route' => '/features/widgets/stats'],
            ['title' => 'Charts',          'route' => '/features/widgets/charts'],
            ['title' => 'Mixed',           'route' => '/features/widgets/mixed'],
            ['title' => 'Tiles',           'route' => '/features/widgets/tiles'],
            ['title' => 'Engage',          'route' => '/features/widgets/engage'],
            ['title' => 'Base Tables',     'route' => '/features/widgets/base-tables'],
            ['title' => 'Advance Tables',  'route' => '/features/widgets/advance-tables'],
            ['title' => 'Feeds',           'route' => '/features/widgets/feeds'],
            ['title' => 'Nav Panels',      'route' => '/features/widgets/nav-panels'],
        ],
    ],
    [
        'title' => 'Icons',
        'icon'  => 'General/Attachment2',
        'submenu' => [
            ['title' => 'SVG Icons',     'route' => '/features/icons/svg'],
            ['title' => 'Custom Icons',  'route' => '/features/icons/custom-icons'],
            ['title' => 'Flaticon',      'route' => '/features/icons/flaticon'],
            ['title' => 'Fontawesome 5', 'route' => '/features/icons/fontawesome5'],
            ['title' => 'Lineawesome',   'route' => '/features/icons/lineawesome'],
            ['title' => 'Socicons',      'route' => '/features/icons/socicons'],
        ],
    ],
    [
        'title' => 'Calendar',
        'icon'  => 'Design/Select',
        'submenu' => [
            ['title' => 'Basic Calendar',     'route' => '/features/calendar/basic'],
            ['title' => 'List Views',         'route' => '/features/calendar/list-view'],
            ['title' => 'Google Calendar',    'route' => '/features/calendar/google'],
            ['title' => 'External Events',    'route' => '/features/calendar/external-events'],
            ['title' => 'Background Events',  'route' => '/features/calendar/background-events'],
        ],
    ],
    [
        'title' => 'Charts',
        'icon'  => 'Media/Equalizer',
        'submenu' => [
            ['title' => 'Apexcharts', 'route' => '/features/charts/apexcharts'],
            [
                'title' => 'amCharts',
                'submenu' => [
                    ['title' => 'amCharts Charts',       'route' => '/features/charts/amcharts/charts'],
                    ['title' => 'amCharts Stock Charts', 'route' => '/features/charts/amcharts/stock-charts'],
                    ['title' => 'amCharts Maps',         'route' => '/features/charts/amcharts/maps'],
                ],
            ],
            ['title' => 'Flot Charts',     'route' => '/features/charts/flotcharts'],
            ['title' => 'Google Charts',   'route' => '/features/charts/google-charts'],
        ],
    ],

    [
        'title' => 'Maps',
        'icon'  => 'Home/Book-open',
        'submenu' => [
            ['title' => 'Google Maps', 'route' => '/features/maps/google-maps'],
            ['title' => 'Leaflet',     'route' => '/features/maps/leaflet'],
            ['title' => 'JQVMap',      'route' => '/features/maps/jqvmap'],
        ],
    ],
    [
        'title' => 'Miscellaneous',
        'icon'  => 'Home/Mirror',
        'submenu' => [
            ['title' => 'Kanban Board',      'route' => '/features/miscellaneous/kanban-board'],
            ['title' => 'Sticky Panels',     'route' => '/features/miscellaneous/sticky-panels'],
            ['title' => 'Block UI',          'route' => '/features/miscellaneous/blockui'],
            ['title' => 'Perfect Scrollbar', 'route' => '/features/miscellaneous/perfect-scrollbar'],
            ['title' => 'Tree View',         'route' => '/features/miscellaneous/treeview'],
            ['title' => 'Bootstrap Notify',  'route' => '/features/miscellaneous/bootstrap-notify'],
            ['title' => 'Toastr',            'route' => '/features/miscellaneous/toastr'],
            ['title' => 'SweetAlert2',       'route' => '/features/miscellaneous/sweetalert2'],
            ['title' => 'Dual Listbox',      'route' => '/features/miscellaneous/dual-listbox'],
            ['title' => 'Session Timeout',   'route' => '/features/miscellaneous/session-timeout'],
            ['title' => 'Idle Timer',        'route' => '/features/miscellaneous/idle-timer'],
            ['title' => 'Cropper',           'route' => '/features/miscellaneous/cropper'],
        ],
    ],
];
